#!/bin/sh

aspell="$(which aspell 2>/dev/null)"
if [ $? -ne 0 ]; then
	echo "error: aspell is not installed"
	exit 1
fi

words=$($aspell --list < "$1")
msg=$(cat "$1")
if [ -n "$words" ]; then
	echo "warning: possible spelling errors:" >&2
	echo "" >&2
	echo "$words" >&2
	echo "" >&2
	echo "correct the message or skip this warning with" >&2
	echo"  git commit --no-verify -m \"$msg\"" >&2
	exit 1
fi
